[tool.poetry]
name = "qa"
version = "0.1.0"
description = ""
authors = ["lhy <dev@lhy.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2"
pandas = "^2.0.0"
openpyxl = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
